import React from "react";
import Table from "./Table";

const Content = () => {
  return (
    <>
      <section className="w-[85%] md:w-[90%] mx-auto pt-20 flex sm:flex-col-reverse justify-between text-[#0D081B]">
        <div className="w-[60%] sm:w-[100%] sm:mt-8">
          <h1 className="text-[32px] mb-2 font-semibold" id="i&d">
            Interpretation and Definitions
          </h1>
          <h2 className="font-semibold text-xl mb-4" id="interpretation">Interpretation</h2>
          <p className="my-4">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <p className="font-semibold text-xl mb-4" id="definitions">Definitions</p>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <p className="mb-2">
            <b className="font-semibold">Account</b> means a unique account
            created for You to access our Service or parts of our Service.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Company</b> (referred to as either "the
            Company", "We", "Us" or "Our" in this Agreement) refers to
            ApplyForMe.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Cookies</b> are small files that are
            placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that
            website among its many uses.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Country</b> refers to: Nigeria.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Device</b> means any device that can
            access the Service such as a computer, a cellphone or a digital
            tablet.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Personal Data</b> is any information
            that relates to an identified or identifiable individual.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Service</b> refers to the Website.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Service Provider</b> means any natural
            or legal person who processes the data on behalf of the Company. It
            refers to third-party companies or individuals employed by the
            Company to facilitate the Service, to provide the Service on behalf
            of the Company, to perform services related to the Service or to
            assist the Company in analyzing how the Service is used.
          </p>
          <p className="mb-2">
            <b className="font-semibold">Usage Data</b> refers to data collected
            automatically, either generated by the use of the Service or from
            the Service infrastructure itself (for example, the duration of a
            page visit).
          </p>
          <p className="mb-2">
            <b className="font-semibold">Website</b> refers to ApplyForMe,
            accessible from{" "}
            <a href="" className="underline">
              applyforme.com
            </a>
          </p>
          <p className="mb-8">
            <b className="font-semibold">You</b> means the individual accessing
            or using the Service, or the company, or other legal entity on
            behalf of which such individual is accessing or using the Service,
            as applicable.
          </p>
          <h1 className="text-[32px] mb-2 font-semibold" id="collecting">
            Collecting and Using Your Personal Data
          </h1>
          <ul className="mb-8">
            <li id="types" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Types of Data Collected
            </li>
            <li id="use" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Use of Your Personal Data
            </li>
            <li id="retention" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Retention of Your Personal Data
            </li>
            <li id="transfer" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Transfer of Your Personal Data
            </li>
            <li id="delete" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Delete Your Personal Data
            </li>
            <li id="disclosure" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Disclosure of Your Personal Data
            </li>
            <li id="security" className="list-disc list-inside text-[18px] leading-10 font-semibold">
              Security of Your Personal Data
            </li>
          </ul>
          <h1 id="children" className="text-[32px] mb-2 font-semibold">Children's Privacy</h1>
          <p className="mb-8">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from our servers.
            <br />
            <br />
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </p>
          <h1 id="links" className="text-[32px] mb-2 font-semibold">
            Links to Other Websites
          </h1>
          <p className="mb-8">
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
            <br /> <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>

          <h1 id="changes" className="text-[32px] mb-2 font-semibold">
            Changes to this Privacy Policy
          </h1>
          <p className="mb-8">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.{" "}
            <br />
            <br />
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy. <br /> <br />
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
          <h1 id="contact" className="text-[32px] mb-2 font-semibold">Contact Us</h1>
          <p>
            If you have any questions about this Privacy Policy, You can contact
            us:
            <br />
            By email: hello@applyforme.com
          </p>
        </div>
        <div className="w-[33%] md:w-[38%] sm:w-[100%]">
          <Table />
        </div>
      </section>
    </>
  );
};

export default Content;
